# This is to generate GraphQL files for Frontend/Lambdas based on 'schema.graphql'.
# Amplify codegen is used to generate GraphQL files out of schema.graphql.
# We don't use other amplify cli at all.
#
# Usage :
# cd first-responder-admin/common
# amplify codegen types
# amplify codegen statements
projects:
  AmplifyFirstResponderAdmin:
    schemaPath: /graphql/schema.graphql
    includes:
      - ../common/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: types/API.ts
        docsFilePath: ./graphql
extensions:
  amplify:
    version: 3